// src/main/webapp/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { NgbModalRef } from '@ng-bootstrap/ng-bootstrap';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Station } from '../entities/station/station.model';
import { StationService } from '../entities/station/station.service';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { Account, LoginModalService, Principal } from '../shared';

@Component({
    selector: 'jhi-home',
    templateUrl: './home.component.html',
    styleUrls: [
        'home.css'
    ]

})
export class HomeComponent implements OnInit {
    account: Account;
    modalRef: NgbModalRef;
    stations: Station[];
    predicate: any;
    reverse: any;
    constructor(
        private principal: Principal,
        private loginModalService: LoginModalService,
        private eventManager: JhiEventManager,
        private stationService: StationService,
        private jhiAlertService: JhiAlertService
        ) {
    }

    sort() {
        const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }

    loadAll() {
        this.stationService.query({
            page: 0,
            size: 100,
            sort: ''}).subscribe(
                (res: HttpResponse<Station[]>) => this.onSuccess(res.body, res.headers),
                (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.account = account;
        });
        this.registerAuthenticationSuccess();

    }

    getStationId(index: number, item: Station) {
        return item.id;
    }

    registerAuthenticationSuccess() {
        this.eventManager.subscribe('authenticationSuccess', (message) => {
            this.principal.identity().then((account) => {
                this.account = account;
            });
        });
    }

    isAuthenticated() {
        return this.principal.isAuthenticated();
    }

    login() {
        this.modalRef = this.loginModalService.open();
    }

    private onSuccess(data, headers) {
        // this.links = this.parseLinks.parse(headers.get('link'));
        // this.totalItems = headers.get('X-Total-Count');
        // this.queryCount = this.totalItems;
        // this.page = pagingParams.page;
        this.stations = data;
    }
    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div class="row">
    <div class="col-md-3">
        <span class="calfire img-fluid rounded"></span>
    </div>
    <div class="col-md-9">
        <h1 class="display-4" jhiTranslate="home.title">Welcome to CalFire Knowledge Management System</h1>
        <p class="lead" jhiTranslate="home.subtitle">This is your homepage</p>

        <div [ngSwitch]="isAuthenticated()">
            <div class="alert alert-success" *ngSwitchCase="true">
                <span *ngIf="account" jhiTranslate="home.logged.message" translateValues="{username: '{{account.login}}'}"> You are logged in as user "{{account.login}}". </span>
                
                <div class="row">
                    <div class="col-xl-3 col-lg-6" *ngFor="let station of stations ;trackBy: getStationId">
                        <jhi-app-stat [bgClass]="'primary'" [icon]="'fa-comments'" [label]=station.name [engines]=station.engines></jhi-app-stat>
                    </div>
        
                </div>
                <hr/>
            </div>

            <div class="alert alert-warning" *ngSwitchCase="false">
                <span jhiTranslate="global.messages.info.authenticated.prefix">To begin, click </span>
                <a class="alert-link" (click)="login()" jhiTranslate="global.messages.info.authenticated.link">sign in</a>
                <!--span jhiTranslate="global.messages.info.authenticated.suffix">, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- User
                    (login="user" and password="user").</span-->
            </div>
            <div class="alert alert-warning" *ngSwitchCase="false">
                <span jhiTranslate="global.messages.info.register.noaccount">You don't have an account yet?</span>
                <a class="alert-link" routerLink="register" jhiTranslate="global.messages.info.register.link">Register a new account</a>
            </div>
          <hr>
            <div class="row">
                <div class="col-xl-3 col-lg-6">
                    <jhi-app-stat [bgClass]="'info'" [icon]="'fa-comments'" [label]=getTotalStations()></jhi-app-stat>
                </div>

           
                <div class="col-xl-3 col-lg-6">
                    <jhi-app-stat [bgClass]="'info'" [icon]="'fa-comments'" [label]=getTotalEngines()></jhi-app-stat>
                </div>

            

            
                <div class="col-xl-3 col-lg-6">
                    <jhi-app-stat [bgClass]="'info'" [icon]="'fa-comments'" [label]=getTotalArticles()></jhi-app-stat>
                </div>

            

           
                <div class="col-xl-3 col-lg-6">
                    <jhi-app-stat [bgClass]="'info'" [icon]="'fa-comments'" [label]=getTotalTags()></jhi-app-stat>
                </div>

            </div>
            <hr />

            <hr>
            <div class="row">
                <div class="col-xl-3 col-lg-6" *ngFor="let station of stations ;trackBy: getStationId">
                    <jhi-app-stat [bgClass]="'secondary'" [icon]="'fa-comments'" [label]=station.name [engines]=station.engines></jhi-app-stat>
                </div>

            </div>
            <hr />
        </div>


    </div>

// src/main/webapp/app/modules/home/home.tsx
import './home.css';

import * as React from 'react';
import { Link } from 'react-router-dom';
import { Translate } from 'react-jhipster';
import { connect } from 'react-redux';

import { getSession } from '../../reducers/authentication';

export interface IHomeProp {
  account: any;
  getSession: Function;
}

export interface IHomeState {
  currentUser: any;
}

export class Home extends React.Component<IHomeProp, IHomeState> {
  constructor(props) {
    super(props);
    this.state = {
      currentUser: props.account
    };
  }

  componentWillMount() {
    this.props.getSession();
  }

  componentWillReceiveProps(nextProps) {
    this.setState({
      currentUser: nextProps.account
    });
  }

  render() {
    const { currentUser } = this.state;

    return (
      <div className="row">
        <div className="col-md-3 pad">
          <span className="hipster img-fluid rounded" />
        </div>
        <div className="col-md-9">
          <h2><Translate contentKey="home.title">Welcome to CalFire KMT</Translate></h2>
          <p className="lead"><Translate contentKey="home.subtitle">This is your homepage</Translate></p>
          {
            (currentUser && currentUser.login) ? (
              <div>
                <div className="alert alert-success">
                  <Translate contentKey="home.logged.message" interpolate={{ username: currentUser.login }}>You are logged in as user </Translate>
                </div>
              </div>
            ) : (
              <div>
                <div className="alert alert-warning">
                  <Translate contentKey="global.messages.info.authenticated.prefix">If you want to </Translate>
                  <Link to="/login" className="alert-link"><Translate contentKey="global.messages.info.authenticated.link">sign in</Translate></Link>
                  <Translate contentKey="global.messages.info.authenticated.suffix">, you can try the default accounts:
                  <br />- Administrator (login=&quot;admin&quot; and password=&quot;admin&quot;)
                  <br />- User (login=&quot;user&quot; and password=&quot;user&quot;).</Translate>
                </div>

                <div className="alert alert-warning">
                  <Translate contentKey="global.messages.info.register.noaccount">You do not have an account yet?</Translate>&nbsp;
                  <a className="alert-link"><Translate contentKey="global.messages.info.register.link">Register a new account</Translate></a>
                </div>
              </div>
            )
          }

          <p>
            <Translate contentKey="home.like">If you like DHSKnowledgeManagemet, do not forget to give us a star on</Translate>
            <a href="https://github.com/dhsynergetech/kmt" target="_blank" rel="noopener noreferrer">Github</a>!
          </p>
        </div>
      </div>
    );
  }
}

const mapStateToProps = storeState => ({
  account: storeState.authentication.account,
  isAuthenticated: storeState.authentication.isAuthenticated
});

const mapDispatchToProps = { getSession };

export default connect(mapStateToProps, mapDispatchToProps)(Home);
